#!/bin/sh

#
# jterm
#
# as called from .cwmrc / cwmrc.*
#

#bind-key MS-t "/home/jmettraux/.x/jterm \"Hack:size=10\" 196x52+0+28 htop -t"

GEOM="$1"; shift
NAME="st__$(tr -cd '[:alnum:]' < /dev/urandom | fold -w 20 | head -n 1)"


if [ -z "$@" ]; then
  /usr/local/bin/urxvt -title "$NAME" -geometry "$GEOM" &
else
  /usr/local/bin/urxvt -title "$NAME" -geometry "$GEOM" -e $@ &
fi

xdotool search --sync --name $NAME key ctrl+alt+shift+f

