#!/bin/sh
# $OpenBSD: Xsetup_0,v 1.8 2020/07/04 13:32:50 matthieu Exp $

prefix="/usr/X11R6"
exec_prefix="${prefix}"

#${exec_prefix}/bin/xsetroot -fg \#6f6f6f -bg \#bfbfbf -bitmap ${prefix}/include/X11/bitmaps/root_weave
#${exec_prefix}/bin/xconsole -geometry 480x130-0-0 -daemon -notify -verbose -fn fixed -exitOnFail

#  install package openbsd-backgrounds
#  then uncomment:
#
# if test -x /usr/local/bin/openbsd-wallpaper
# then
# 	/usr/local/bin/openbsd-wallpaper
# fi

# sxpm OpenBSD.xpm &

${exec_prefix}/bin/setxkbmap jp
${exec_prefix}/bin/xsetroot -solid black

